### ISSUE TITLE
Frontend revisited. Sorry

### ISSUE THREAD

**Issue by deljones** [Flynntes/Sleeky#112]
Hello,

I know that this issue has been already mentioned but after trying out the editing of the header.php file I am still not getting the nice front end that is shown in the demo for Sleeky. I have attached what I get, which is ugly.

<img width="1315" alt="Screenshot 2022-07-06 at 12 21 36" src="https://user-images.githubusercontent.com/2440463/177540239-db517cb6-b66e-4607-9d61-b924206eb194.png">

Can anyone shed any more light on what might be happening here and a resolution.

Best wishes

Dj

**Comment by deljones** [comment]
@[shrey2199]

Thanks for the fix....

**Comment by zuohaoda** [comment]
How did you solve it, my friend
