### ISSUE TITLE
Custom short url

### ISSUE THREAD

**Issue by madebydirk** [Flynntes/Sleeky#13]
I really love the look of sleeky, but I also really miss the option to choose a custom short url. 
Is it possible to make that field optional?

Thank you so much

**Comment by Flynntes** [comment]
Thanks for the suggestion! Just pushed an update that adds this feature :)
Let me know if you have any troubles

**Comment by madebydirk** [comment]
Heyy awesome!

I did some quick and dirty stuff myself but need sommething good desperately!

Will let you know of my findings.
Great you picked it up, kudos.

Met vriendelijke groet,

Dirk Kuijt

[https://madebydirk.com/handtekening/images/facebook.png]<https://fb.me/madebydirk>     [https://madebydirk.com/handtekening/images/twitter.png] <https://twitter.com/madebydirk>       [https://madebydirk.com/handtekening/images/instagram.png] <https://instagr.am/madebydirk>      [https://madebydirk.com/handtekening/images/pinterest.png] <https://pinterest.com/madebydirkcom>        [Website] <https://madebydirk.com/>

On 22 Jul 2019, at 09:33, Flynn Tesoriero <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the suggestion! Just pushed an update that adds this feature :)
Let me know if you have any troubles
