### ISSUE TITLE
backend for plugins

### ISSUE THREAD

**Issue by joshp23** [Flynntes/Sleeky#19]
I wrote a good handful of plugins to work with the stock backend and used the infos.css and infos.js in order to create nice tabbed <div> sections in my plugin admin pages. In the stock interface this works as expected, however with sleeky backend enabled the tabs look like the old style, and not like the updated sleeky backend style. Any pointers on how to achieve making these tabs take on the sleeky style? Everything else works like a charm.

**Comment by Flynntes** [comment]
Hey Josh,
Which plugin could I use to test this?
Thanks

**Comment by joshp23** [comment]
Most of mine. Try this one, [cAuth](https://github.com/joshp23/YOURLS-cAuth).

**Comment by Flynntes** [comment]
Hey there, I believe I have fixed this issue now. I tried a couple of your other plugins too and they seem to work well with the theme. Let me know if you spot any other issues. Thanks for submitting the issue

**Comment by joshp23** [comment]
nice work on the tabs, did you get any odd behavior concerning the `<div id="wrap">` styling? In sleeky it seems to put significant padding into the picture 
![Screenshot from 2019-10-05 09-33-48](https://user-images.githubusercontent.com/7341917/66255634-f2018b00-e753-11e9-8047-590183c973d6.png)
