### ISSUE TITLE
Short link overlaps the copy button on mobile.

### ISSUE THREAD

**Issue by jirkapas** [Flynntes/Sleeky#20]
Hi,
The short link overlaps the copy button on smaller divices. 
![Screenshot_20190923-121617_Chrome](https://user-images.githubusercontent.com/7852704/65418272-62c3b180-ddfc-11e9-912d-f1114c020e79.jpg)
Still, this is an awesome project. Thank you.

**Comment by Flynntes** [comment]
Thanks for submitting this :D
I'll work on a fix

**Comment by Flynntes** [comment]
This has been fixed in the latest version. Thanks for submitting the issue.
