### ISSUE TITLE
Weird Lastpass Bug

### ISSUE THREAD

**Issue by JoaoBernardoo** [Flynntes/Sleeky#21]
Hi,

Just put in the sleeky-backend on our YOURLS website and it is working well, the only issue we are having is an unexpected behaviour with the Lastpass browser extension. You can see what happens in the attached image.
![weird_lastpass_glitch](https://user-images.githubusercontent.com/19581988/65906991-7be6d800-e391-11e9-9a45-77a2028e4b9a.JPG)
Wondering if you have encountered this and if you have any idea how to fix the issue. Thanks.

**Comment by garytou2** [comment]
I have also run into this bug and haven't been able to figure out a solution.

**Comment by Flynntes** [comment]
Just pushed up a new version fixing this issue. I was targeting all images with css (very lazy), I'm now just targeting the logo image.
