### ISSUE TITLE
https (SSL) issues

### ISSUE THREAD

**Issue by mlopezcoria** [Flynntes/Sleeky#22]
I'm using https for the frontend and it doesn't load all assets properly.
I've tried defining the `siteURL` as `http` and `https`, but it doesn't work neither way.

![Screenshot](https://user-images.githubusercontent.com/15494802/65912551-c45bc100-e3a4-11e9-8244-d09730e004dc.png)

On the other hand, backend is working correctly.

**Comment by freaky33** [comment]
I dont have SSL enabled and it still happens. Any fixes?

**Comment by Flynntes** [comment]
Hey there,
Let me know if you're still experiencing this issue and I can look into it further.
