### ISSUE TITLE
Debug data obfuscated by sidebar in backend

### ISSUE THREAD

**Issue by joshp23** [Flynntes/Sleeky#23]
As title suggests, debug data is obfuscated by the sidebar with sleeky enabled
![Screenshot from 2019-10-05 09-41-50](https://user-images.githubusercontent.com/7341917/66255717-f4181980-e754-11e9-91f0-21947e40c3ed.png)

**Comment by Flynntes** [comment]
Thanks for this. Fixed in 2.3.
