### ISSUE TITLE
Probably no CSS on frontend

### ISSUE THREAD

**Issue by TheColin21** [Flynntes/Sleeky#27]
Just setup Sleeky together with the current YOURLS v1.7.4.
Backend looks great but frontend doesn't seem to have any CSS on it. The configurations made in config.php work but all elements are just listed in the top left in front of the standard blue background. I was able to set a background image but it still looks kind of shitty.

**Comment by olpo24** [comment]
I've the same "problem". 
In the install instructions is one thing missing.
We have to edit the config.php in the frontend folder.

**Comment by TheColin21** [comment]
I did edit the config.php. What exactly should I change?

Am 27. November 2019 14:52:07 MEZ schrieb olpo24 <notifications@github.com>:
>I've the same "problem". 
>In the install instructions is one thing missing.
>We have to edit the config.php in the frontend folder. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Flynntes/Sleeky/issues/27#issuecomment-559095937

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by olpo24** [comment]
Aufpassen ;-) nicht die config.php im root Ordner deiner YOURLS installation, sondern die config.php im Ordner Frontend. 
Da gibt es in Zeile 6 und 7 den Eintrag:

`// Site URL (no trailing slash)
define('siteURL', 'http://localhost:8888');`

**Comment by TheColin21** [comment]
Ich weiß, die habe ich angepasst.

Am 27. November 2019 15:35:22 MEZ schrieb olpo24 <notifications@github.com>:
>Aufpassen ;-) nicht die config.php im root Ordner deiner YOURLS
>installation, sondern die config.php im Ordner Frontend. 
>Da gibt es in Zeile 6 und 7 den Eintrag:
>
>`// Site URL (no trailing slash)
>define('siteURL', 'http://localhost:8888');`
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Flynntes/Sleeky/issues/27#issuecomment-559112728

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by TheColin21** [comment]
ok nvm ich hab das s an https vergessen

Am 27. November 2019 15:35:22 MEZ schrieb olpo24 <notifications@github.com>:
>Aufpassen ;-) nicht die config.php im root Ordner deiner YOURLS
>installation, sondern die config.php im Ordner Frontend. 
>Da gibt es in Zeile 6 und 7 den Eintrag:
>
>`// Site URL (no trailing slash)
>define('siteURL', 'http://localhost:8888');`
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Flynntes/Sleeky/issues/27#issuecomment-559112728

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by olpo24** [comment]
Ok....und geht immer noch nicht? Bei mir hat das funktioniert. Magst du mir mal die URL deiner Installation geben?

**Comment by TheColin21** [comment]
ja
