### ISSUE TITLE
Can't add recaptcha

### ISSUE THREAD

**Issue by FuzzyThor** [Flynntes/Sleeky#28]
I tried to add recaptcha but the styling won't allow for it.

**Comment by Flynntes** [comment]
Hey there,
Could you explain further what you mean?

**Comment by FuzzyThor** [comment]
Ok better yet how can we add the recaptcha plugin to the public page preventing spam

**Comment by kurnias** [comment]
please add recaptcha in public frontend page

**Comment by Flynntes** [comment]
Thanks guys, added in v2.4.0 :)
