### ISSUE TITLE
How to change the homepage address?

### ISSUE THREAD

**Issue by wyfang** [Flynntes/Sleeky#29]
Because I use the website for another purpose, it is not index.php. I changed it to url.php, but I found the code after shortening the address:

```
<div class="close noselect">
<a href="https://xxxx.xxx/"><i class="material-icons">close</i></a>
</div>
```

SO,how can I change to `"https://xxxx.xxx/url.php"`

**Comment by Flynntes** [comment]
Hey,
This is fixed in version 2.3.
Thanks
