### ISSUE TITLE
Custom public pages

### ISSUE THREAD

**Issue by robsd** [Flynntes/Sleeky#30]
It would be cool to include some documentation on how to include our own public pages (terms and conditions, privacy policy etc...)

Also, a separate public stats page would be awesome, don't really want users being shown a link to the admin panel and yourls documentation

**Comment by Flynntes** [comment]
Hey Rob,
Links to the admin area will be hidden on the stats page for users who aren't authenticated in version 2.3. Thanks for the idea.
For now, public pages can just be created as plain old .html or .php files, but I do agree that it would be to include some templates/documentation on this. Feel free to create a pull request if you do any work on this.
Thanks :)
