### ISSUE TITLE
2.2.1 still showing for version 2.3.0

### ISSUE THREAD

**Issue by robsd** [Flynntes/Sleeky#32]
Just updated to version 2.3.0 by following the same installation process as 2.2.1 but overwriting files

The version 2.2.1 is still showing in the plugins list for version 2.3.0

Did I do something wrong?

![image](https://user-images.githubusercontent.com/8268467/71977418-a78b2100-3210-11ea-9958-68a7518e997d.png)

**Comment by master3395** [comment]
You're not wrong.
But the version number is just a small number.
You can change your self if you want to.

![image](https://user-images.githubusercontent.com/4199669/72114453-d655e400-3343-11ea-9abe-4332bf06fb39.png)


> Just updated to version 2.3.0 by following the same installation process as 2.2.1 but overwriting files
> 
> The version 2.2.1 is still showing in the plugins list for version 2.3.0
> 
> Did I do something wrong?
> 
> ![image](https://user-images.githubusercontent.com/8268467/71977418-a78b2100-3210-11ea-9958-68a7518e997d.png)

**Comment by Flynntes** [comment]
My bad, thanks for catching this. All fixed now thanks to @master3395
