### ISSUE TITLE
After log in to the admin page returns a blank page and have to go back can sleeky display the admin page

### ISSUE THREAD

**Issue by MFYDev** [Flynntes/Sleeky#35]
Hi there ,

After 2.3.0, every version of sleeky has the same problem that I cannot log in to the admin page in one time. I have to click on the log in button, and got a blank page, then I have to click the "go back" button on my browser, only in this way can it display the admin page.

Why this happenes? I think this is not my problem cause the setting has nothing wrong.

**Comment by FanyangMengDev** [comment]
I made a screencast and please have a look on how it happenes on my side.

I think this can help demonstrate it more clearly

![ezgif-3-d87a0e395076](https://user-images.githubusercontent.com/53750381/72658373-13c50c00-39eb-11ea-89e8-14a48dc3777e.gif)

**Comment by Beltshassar** [comment]
I've encountered the same problem.
It seems to be a problem with Chrome, as the problem is not present in Firefox.

**Comment by hdlineage** [comment]
Same problem here with chrome. After a successful log in the page becomes blank.
A POST request was sent and the response was empty. No error code in the browser console.

**Comment by FanyangMengDev** [comment]
@Beltshassar Thanks for your confirm and I just change my default browser to firefox which really enhance my experience than Chrome. From my perspective I think Firefox is better to use than Chrome now. : )

@hdlineage Yes, really weird that there is no error code in console. But you can following @Beltshassar 's advice to use Firefox. I found that this problem really does not happen on Firefox.

**Comment by sathish1981** [comment]
@Flynntes : Do you have any idea why the '/?' is added extra from default login redirect to admin page?
Actually in the default YOURLS, afetr login the page will redirect like https://<domain name>/admin but after installing sleeky it redirects as https://<domain name>/admin/? 
So its adding additional '/?' character to the redirects. 

Can you please help us to find exactly which line of code doing this?

**Comment by BenJamesAndo** [comment]
Any updates on this? I'm also experiencing this same issue with Sleeky on Chrome.

**Comment by sathish1981** [comment]
@BenJamesAndo @Beltshassar 
Actually I fixed this issue on my instance. For some strange reason the code is looking for Allowed Protocols in config.php. So please add the below line in config.php
$yourls_allowedprotocols = array( 'http://', 'https://');

It fixed my problem :)

**Comment by FanyangMengDev** [comment]
@sathish1981 Wow mate thank you so much for sharing your solution. I did what you told us and it fixed my problem too. You are excellent! Bravo!

**Comment by hdlineage** [comment]
> @BenJamesAndo @Beltshassar
> Actually I fixed this issue on my instance. For some strange reason the code is looking for Allowed Protocols in config.php. So please add the below line in config.php
> $yourls_allowedprotocols = array( 'http://', 'https://');
> 
> It fixed my problem :)

Fixed my problem as well. Just curious, how did you figure this out?

**Comment by sathish1981** [comment]
> > @BenJamesAndo @Beltshassar
> > Actually I fixed this issue on my instance. For some strange reason the code is looking for Allowed Protocols in config.php. So please add the below line in config.php
> > $yourls_allowedprotocols = array( 'http://', 'https://');
> > It fixed my problem :)
> 
> Fixed my problem as well. Just curious, how did you figure this out?

He He... Feeling lucky mate :) I got the an error while running my local xampp instance in debug mode.
