### ISSUE TITLE
Unable to close reCAPTCHA

### ISSUE THREAD

**Issue by wyfang** [Flynntes/Sleeky#36]
![TIM截图20200119214302](https://user-images.githubusercontent.com/17900420/72682108-b329f200-3b04-11ea-890a-7ac9f83143c4.png)

As we all know, reCAPTCHA is not accessible in China. I tried to turn off reCAPTCHA, but it seems to have no effect. Is define ("enableRecaptcha", true); set to false? Still commenting it out has no effect.

**Comment by Yonninout** [comment]
Hi,

I made a pull request for that 

https://github.com/Flynntes/Sleeky/pull/37

there was a if missing in a js script
