### ISSUE TITLE
Frontend shortner doesn't work

### ISSUE THREAD

**Issue by breatfr** [Flynntes/Sleeky#38]
Hello,

Thank you for your themes, very good job but frontend shortner doesn't work if i disable reCaptcha in config.php.

When I try it and click on Shorten, nothing append.

No problem in backend.

I use the lastest versions of your themes and yourls.

You can try it by yourself here : [https://go.breat.fr](https://go.breat.fr).

**Comment by Flynntes** [comment]
Hi there,
Thank you! Looking at your website, I believe you've fixed the issue.
Let me know if you need any help.
Cheers

**Comment by breatfr** [comment]
Hello, yes I fixed it with adding reCaptcha :)
