### ISSUE TITLE
Admin-Interface does not work correctly.

### ISSUE THREAD

**Issue by manuelfrick** [Flynntes/Sleeky#5]
Hi, 

the admin-panel does not work correctly.
See screenshot.

Yours,
Manuel

![bildschirmfoto 2018-08-19 um 17 20 04](https://user-images.githubusercontent.com/5370598/44310299-5d638e80-a3d4-11e8-83c9-a619e550e52e.png)

**Comment by Flynntes** [comment]
Hey Manuel, 
Which version of YOURLS are you using?
Do you have any other plugins running? I'm unable to replicate your issue.
