### ISSUE TITLE
config.php :: Notice: Undefined variable /frontend/config.php on line 7

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [Flynntes/Sleeky#51]
This is undefined and trying to find out where's that? I have checked wiki but didn't find any info about this. How to fix this notice?
![image](https://user-images.githubusercontent.com/7280837/82411048-735f2100-9a8a-11ea-9f99-b86bc6ced58a.png)

**Comment by Abd-Ur-Rehman** [comment]
I have removed this theme.

**Comment by aaryanporwal** [comment]
I have the same issue :(

**Comment by josteinh** [comment]
changed `define('siteURL', $YOURLS_SITE);`
to `define('siteURL', 'https://my.site.url');`

**Comment by aaryanporwal** [comment]
Oh, lol didn't realize that, thanks @josteinh !
