### ISSUE TITLE
Save-Button on mobiledevice is hidden

### ISSUE THREAD

**Issue by geimist** [Flynntes/Sleeky#6]
It's the same with portrait or landscape / iPhone or iPad. 

![img_3fcddb88a430-1 kopie](https://user-images.githubusercontent.com/29315520/46353617-f258d900-c65c-11e8-85d5-72804f3f1138.png)

**Comment by Flynntes** [comment]
Working on this, will release a mobile theme soon 👍

**Comment by Flynntes** [comment]
All fixed! Admin interface is now responsive :)

**Comment by geimist** [comment]
Thank you very much 👍
