### ISSUE TITLE
Frontend CSS failed

### ISSUE THREAD

**Issue by skeith** [Flynntes/Sleeky#8]
The link to the CSS on header is defined this way

    <link rel="stylesheet" href="<?php echo siteURL ?>assets/css/base.css">
    <link rel="stylesheet" href="<?php echo siteURL ?>assets/css/mobile.css">
    <link rel="stylesheet" href="<?php echo siteURL ?>assets/css/tablet.css">
    <link rel="stylesheet" href="<?php echo siteURL ?>assets/css/desktop.css">

However, the console says those are all 404 
![image](https://user-images.githubusercontent.com/340284/48975493-4b1c7f00-f0ac-11e8-8177-6d1ca866fd1b.png)
Which I assume, the `Gruntfile.js` failed to create those files.

On the occasion it successfully creates the files however, I got another issue about `Resource interpreted as stylesheet but transferred with MIME type text/html` which caused by `https://DOMAIN/assets/css/base.css` redirects to `https://DOMAIN/`

Any help on this please?

I am using YOURLS 1.7.2 on nginx

**Comment by dpalic** [comment]
same issue here.

the demo site contains the needed files
https://sleeky.flynntes.com/demo/

**Comment by TonyRL** [comment]
This is why the CSS is broken.
https://github.com/Flynntes/Sleeky/commit/4bf17c9fee301e1461a08baa7aac69b13a7b77fe

**Comment by Flynntes** [comment]
Hi @skeith & @dpalic,
It looks like I put the wrong files in .gitignore - my bad. All should be fixed now in v2.1.1.
Let me know if it doesn't work 👍

**Comment by warsix4** [comment]
For others who encounter this issue, the Site URL in `config.php` needs to end with a `/` or the CSS will fail to load.
