### ISSUE TITLE
Admin isn't mobile responsive

### ISSUE THREAD

**Issue by wafflehacker** [Flynntes/Sleeky#9]
Admin interface does not look good on mobile at all. It isn't responsive to resolution.

**Comment by mtsmayad** [comment]
I wish u update the backen css to make it responsive and to update the front end too :)

**Comment by Flynntes** [comment]
Working on this now, should be ready very soon 😃

**Comment by Flynntes** [comment]
Hi there, admin interface is now responsive on mobile.
